### ISSUE TITLE
Mac OSX

### ISSUE THREAD

**Issue by flxK** [springweblobby/swl-qt#18]
I just made a build of swl-qt that allows me to play zero-k on OSX. Because there are many bugs in the mac version (you can't even build it without modifying the source code) i would offer to help fixing these bugs. Please let me know if my contributions would be accepted.

**Comment by db81** [comment]
Do make a PR with your changes. If you make a wiki page documenting how to build it, that would be nice too.

Back in the day when spring didn't have builds for mac @wagonrepairer built a version and it worked (if you ignore the PADDING hacks) as described in https://github.com/springweblobby/swl-website/wiki/QtDevelopment#mac-qt-development.

I'm travelling and have intermittment web access so keep that in mind if I don't comment for a day or two.
