### ISSUE TITLE
BA ChickenDEF game is not shown in battles games

### ISSUE THREAD

**Issue by FabriceFABS** [springweblobby/swl-qt#24]
For instance, BAR can enable ChickenDEFENSE mode in it's own game.

But for BA, it's a different mod to play BA ChickenDEFENSE.
We can't see BA CD games. Can you add the possibility to check it in settings ?
[ACE]Synchrone is BA CD game.

Thx

**Comment by db81** [comment]
It's not a big deal, but this should've been posted to springweblobby/swl-website issues, swl-qt tracker is for bugs in the C++ part behind swl. When unsure, use swl-website.
