### ISSUE TITLE
Libboost issue

### ISSUE THREAD

**Issue by 9joshua** [springweblobby/swl-qt#28]
Web Lobby fails to start with the following message:
`./weblobby: error while loading shared libraries: libboost_filesystem.so.1.55.0: cannot open shared object file: No such file or directory`
The file exists in weblobby-1.5-linux64/lib
I then installed libboost-all-dev which installed version 1.58. Still have the same error. Not sure how to fix this issue. This in on a fresh Ubuntu 16.04 install. Had the same issue with 14.04 on another computer.

**Comment by db81** [comment]
You're running the weblobby script outside of lib, not the executable in lib, right? The script is supposed to set LD_LIBRARY_PATH.

**Comment by 9joshua** [comment]
The Run Weblobby.desktop file does not work. I suppose, then, that is the issue. I receive the error above when running the executable from within the lib folder. Here is the message when running the desktop file in a terminal:
`./Run Weblobby.desktop: line 1: [Desktop: command not found`
`./Run Weblobby.desktop: line 6: Weblobby: command not found`
`./Run Weblobby.desktop: line 9: Weblobby: command not found`

And if I just double click the file:
`There was an error launching the application.`

The contents of the file:
```
[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Terminal=false
Name=Run Weblobby
Exec=./lib/weblobby
Icon=lib/icon.png
Name[en_NZ]=RunWeblobby
```
Perhaps I am doing something wrong. It worked fine in the past before upgrading to Ubuntu 16.04 from 12.04. I have another 14.04 machine with the same issue. Could it be a desktop file format issue with Ubuntu > 12.04?

**Comment by db81** [comment]
I don't mean the .desktop file, I mean a file named "weblobby" next to it. That's a script that does some necessary setup. Run it with `./weblobby`. Running `./lib/weblobby` isn't supposed to work.

**Comment by 9joshua** [comment]
Thanks. That worked just fine. Once I ran `./weblobby` in a terminal, Unbuntu was able to use the .desktop file as well.
